#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : R-Formula
Version  : 1.2.3
Release  : 10
URL      : https://cran.r-project.org/src/contrib/Formula_1.2-3.tar.gz
Source0  : https://cran.r-project.org/src/contrib/Formula_1.2-3.tar.gz
Summary  : Extended Model Formulas
Group    : Development/Tools
License  : GPL-2.0 GPL-3.0
BuildRequires : clr-R-helpers

%description
right-hand side and/or multiple responses on the left-hand side

%prep
%setup -q -c -n Formula

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1525368111

%install
rm -rf %{buildroot}
export SOURCE_DATE_EPOCH=1525368111
export LANG=C
export CFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FCFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export FFLAGS="$CFLAGS -O3 -flto -fno-semantic-interposition "
export CXXFLAGS="$CXXFLAGS -O3 -flto -fno-semantic-interposition "
export AR=gcc-ar
export RANLIB=gcc-ranlib
export LDFLAGS="$LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=haswell -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=haswell -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library Formula
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=skylake-avx512 -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=skylake-avx512 -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --no-test-load --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library Formula
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library Formula
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc -l %{buildroot}/usr/lib64/R/library Formula|| : 
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :


%files
%defattr(-,root,root,-)
/usr/lib64/R/library/Formula/CITATION
/usr/lib64/R/library/Formula/DESCRIPTION
/usr/lib64/R/library/Formula/INDEX
/usr/lib64/R/library/Formula/Meta/Rd.rds
/usr/lib64/R/library/Formula/Meta/features.rds
/usr/lib64/R/library/Formula/Meta/hsearch.rds
/usr/lib64/R/library/Formula/Meta/links.rds
/usr/lib64/R/library/Formula/Meta/nsInfo.rds
/usr/lib64/R/library/Formula/Meta/package.rds
/usr/lib64/R/library/Formula/Meta/vignette.rds
/usr/lib64/R/library/Formula/NAMESPACE
/usr/lib64/R/library/Formula/NEWS
/usr/lib64/R/library/Formula/R/Formula
/usr/lib64/R/library/Formula/R/Formula.rdb
/usr/lib64/R/library/Formula/R/Formula.rdx
/usr/lib64/R/library/Formula/doc/Formula.R
/usr/lib64/R/library/Formula/doc/Formula.Rnw
/usr/lib64/R/library/Formula/doc/Formula.pdf
/usr/lib64/R/library/Formula/doc/index.html
/usr/lib64/R/library/Formula/help/AnIndex
/usr/lib64/R/library/Formula/help/Formula.rdb
/usr/lib64/R/library/Formula/help/Formula.rdx
/usr/lib64/R/library/Formula/help/aliases.rds
/usr/lib64/R/library/Formula/help/paths.rds
/usr/lib64/R/library/Formula/html/00Index.html
/usr/lib64/R/library/Formula/html/R.css
